<a href="https://colab.research.google.com/github/NSPFD/PYTHON-PROGRAMMING-TASK-RELATED-WORK-AND-ITS-BASICS/blob/main/numpy_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment 1: Numpy - Temperature Data Analysis

In this assignment, you will analyze temperature data for Kathmandu city over two weeks. Follow the tasks below to complete the assignment.

### Task 1: Calculate the average temperature for each week
Use the provided data to calculate the average temperature for Week 1 and Week 2.

In [1]:
import numpy as np

week1_temp = np.array([15.5, 16.8, 18.1, 17.3, 19.2, 20.5, 21.2])
week2_temp = np.array([22.1, 23.4, 22.8, 24.0, 23.5, 24.8, 25.1])

# Calculate the average temperature for each week
# Calculate the average temperature for each week
avg_week1 = np.mean(week1_temp)
avg_week2 = np.mean(week2_temp)

print("Average temperature for Week 1:", avg_week1)
print("Average temperature for Week 2:", avg_week2)

Average temperature for Week 1: 18.37142857142857
Average temperature for Week 2: 23.67142857142857


### Task 2: Find the day with the highest temperature in each week
Use Numpy functions to determine which day had the highest temperature in each week.

In [2]:
# Find the day with the highest temperature in each week
import numpy as np

week1_temp = np.array([15.5, 16.8, 18.1, 17.3, 19.2, 20.5, 21.2])
week2_temp = np.array([22.1, 23.4, 22.8, 24.0, 23.5, 24.8, 25.1])

# Find the index of the day with the highest temperature for each week
highest_temp_day_week1 = np.argmax(week1_temp)
highest_temp_day_week2 = np.argmax(week2_temp)

# Assuming Monday is the first day, calculate the day of the week
days_of_week = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]

print("Day with highest temperature in Week 1:", days_of_week[highest_temp_day_week1])
print("Day with highest temperature in Week 2:", days_of_week[highest_temp_day_week2])

Day with highest temperature in Week 1: Sunday
Day with highest temperature in Week 2: Sunday


### Task 3: Calculate the temperature difference between the two weeks for each day
Find the difference in temperature between the same day in Week 1 and Week 2.

In [3]:
# Calculate the temperature difference between corresponding days of Week 1 and Week 2
import numpy as np

week1_temp = np.array([15.5, 16.8, 18.1, 17.3, 19.2, 20.5, 21.2])
week2_temp = np.array([22.1, 23.4, 22.8, 24.0, 23.5, 24.8, 25.1])

# Calculate the temperature difference between the two weeks for each day
temp_diff = week2_temp - week1_temp

print("Temperature difference between Week 2 and Week 1 for each day:")
print(temp_diff)

Temperature difference between Week 2 and Week 1 for each day:
[6.6 6.6 4.7 6.7 4.3 4.3 3.9]


### Task 4: Reshape the temperature data to represent 2 weeks by 7 days
Reshape the temperature data so that each row represents a week, and each column represents a day.

In [4]:
# Reshape the temperature data to 2x7
import numpy as np

week1_temp = np.array([15.5, 16.8, 18.1, 17.3, 19.2, 20.5, 21.2])
week2_temp = np.array([22.1, 23.4, 22.8, 24.0, 23.5, 24.8, 25.1])

# Combine the two weeks into a single array
all_temps = np.array([week1_temp, week2_temp])

# Reshape the array to have 2 rows (weeks) and 7 columns (days)
reshaped_temps = all_temps.reshape(2, 7)

print(reshaped_temps)

[[15.5 16.8 18.1 17.3 19.2 20.5 21.2]
 [22.1 23.4 22.8 24.  23.5 24.8 25.1]]


### Task 5: Display the reshaped data in a table format
Create a table that shows the day of the week and temperatures from both weeks.

In [5]:
# Display the reshaped data in a table format
import numpy as np
import pandas as pd

week1_temp = np.array([15.5, 16.8, 18.1, 17.3, 19.2, 20.5, 21.2])
week2_temp = np.array([22.1, 23.4, 22.8, 24.0, 23.5, 24.8, 25.1])

# Combine the data into a single array
combined_temp = np.concatenate([week1_temp, week2_temp])

# Create a list of days for both weeks
days = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'] * 2

# Create a DataFrame for better visualization
data = {'Day': days, 'Temperature': combined_temp}
df = pd.DataFrame(data)

# Display the DataFrame as a table
print(df)

    Day  Temperature
0   Mon         15.5
1   Tue         16.8
2   Wed         18.1
3   Thu         17.3
4   Fri         19.2
5   Sat         20.5
6   Sun         21.2
7   Mon         22.1
8   Tue         23.4
9   Wed         22.8
10  Thu         24.0
11  Fri         23.5
12  Sat         24.8
13  Sun         25.1
